# Generated by Django 6.0.3 on 2026-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=1)),
                ('datenaissance', models.DateField()),
            ],
        ),
    ]
