# Generated by Django 6.0.3 on 2026-03-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eleves',
            new_name='Eleve',
        ),
    ]
